package de.wald_ohne_blaetter.gamelibrary.gamegenrereference;

/**
 * This is the reference array for the player and the genre
 *
 * @author Luke Effer
 * @version 0.0.1
 * @since 2025-09-15
 */


import de.wald_ohne_blaetter.gamelibrary.game.Game;
import de.wald_ohne_blaetter.gamelibrary.gamegenre.GameGenre;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class GameGenreReference
{
    @Id
    private Long id;

    /**
     * Unique ID of the game. Automatically generated by the database.
     * imported as foreign key
     */
    @ManyToOne
    @JoinColumn(name = "game_id")
    private Game game_id;

    /**
     * Unique ID of the game genre. Automatically generated by the database.
     * imported as foreign key
     */
    @ManyToOne
    @JoinColumn(name = "game_genre_id")
    private GameGenre game_genre_id;
}
