package de.wald_ohne_blaetter.gamelibrary.gamegenrereference;

import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class GameGenreReference
{
    /**
     * reference array
     *
     * Unique ID of the game. Automatically generated by the database.
     * imported as foreign key
     */

    /**
     * Unique ID of the game genre. Automatically generated by the database.
     * imported as foreign key
     */
}
