package de.wald_ohne_blaetter.gamelibrary.playeropinion;

import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PlayerOpinion
{
    /**
     * Unique ID of the player. Automatically generated by the database, imported as a foreign key
     */

    /**
     * Unique ID of the game. Automatically generated by the database, imported as a foreign key
     */

    /**
     * The last time the game was played. Can be empty
     * Exit-Games should refer to this position for the group of players.
     */
    private Date player_opinion_date;

    /**
     * the preferences of the players. "What do they like more?"
     * It is measured by a value range, low is bad, high is liked
     */
    private String player_opinion_preferences;

    /**
     * the complexity of a game. "How difficult is it to play?"
     * It is measured by a value range, low is bas, high is liked
     */
    private String player_opinion_complexity;

    /**
     * The reason why a game is not liked by someone.
     * This should present the possibility to adjust the game to the preferences and wishes of the players, if possible.
     */


}
