package de.wald_ohne_blaetter.gamelibrary.player;

import de.wald_ohne_blaetter.gamelibrary.address.Address;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.aspectj.weaver.ast.Var;

/**
 * Represents a player in the game library.
 * <p>
 * This class is used as a JPA entity to store relevant information about a player.
 * </p>
 *
 * @author Luke Effer
 * @version 0.0.1
 * @since 2025-09-15
 */


@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Player
{

    /**
     * Unique ID of the player. Automatically generated by the database.
     */
    @Id
    private Long player_id;

    /**
     * Name of the player. Cannot be empty
     */
    private String player_name;

    /**
     * First name of the player. Cannot be empty
     */
    private String player_first_name;

    /**
     * Address of the player with a unique ID. Automatically generated by the database, imported as a foreign Key
     */
    @ManyToOne
    @JoinColumn(name = "address_id")
    private Address address_id;

}
