package de.wald_ohne_blaetter.gamelibrary.player;

import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.aspectj.weaver.ast.Var;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Player
{

    /**
     * Unique ID of the player. Automatically generated by the database.
     */


    /**
     * Name of the player. Cannot be empty
     */
    private String player_name;

    /**
     * First name of the player. Cannot be empty
     */
    private String player_first_name;

    /**
     * Address of the player with a unique ID. Automatically generated by the database, imported as a foreign Key
     */

}
