package de.wald_ohne_blaetter.gamelibrary.gamegenre;

/**
 * Represents a genre in the game library.
 * <p>
 * This class is used as a JPA entity to store relevant information about a genre.
 * </p>
 *
 * @author Luke Effer
 * @version 0.0.1
 * @since 2025-09-15
 */

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;



@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class GameGenre
{
    /**
     * Unique ID of the genre of a game (card game, exit game... etc.) Automatically generated by the database.
     * Primary Key
     */
    @Id
    private Long genre_id;


    /**
     * Name of the game genre. Cannot be empty
     */
    private String genre_name;

    /**
     * Description of the game genre. Cannot be empty
     */
    private String genre_description;
}
