package de.wald_ohne_blaetter.gamelibrary.gamegenre;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;



@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class GameGenre
{
    /**
     * Unique ID of the genre of a game (card game, exit game... etc.) Automatically generated by the database.
     * Primary Key
     */
    @Id
    private Long id;


    /**
     * Name of the game genre. Cannot be empty
     */
    private String game_genre_name;

    /**
     * Description of the game genre. Cannot be empty
     */
    private String game_genre_description;
}
