package de.wald_ohne_blaetter.gamelibrary.publisher;

/**
 * Represents a publisher in the game library.
 * <p>
 * This class is used as a JPA entity to store relevant information about a publisher.
 * </p>
 *
 * @author Luke Effer
 * @version 0.0.1
 * @since 2025-09-15
 */

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Publisher
{
    /**
     * Unique ID of a publisher of games. Automatically generated by the database.
     * Primary Key
     */
    @Id
    private Integer publisher_id;

    /**
     * Name of the publisher. Cannot be empty
     */
    private String publisher_name;

    /**
     * Website of the publisher. Can be empty
     */
    private String publisher_website;
}
