package de.wald_ohne_blaetter.gamelibrary.publisher;

import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Publisher
{
    /**
     * Unique ID of a publisher of games. Automatically generated by the database.
     * Primary Key
     */

    /**
     * Name of the publisher. Cannot be empty
     */
    private String publisher_name;

    /**
     * Website of the publisher. Can be empty
     */
    private String publisher_website;
}
