package de.wald_ohne_blaetter.gamelibrary.address;

import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Address
{
    /**
     * Unique ID of the address. Automatically generated by the database.
     * For locating where the game is stored
     */

    /**
     * The street. Cannot be empty
     */
    public String address_street;

    /**
     * house number. Cannot be empty
     */
    public String address_house_number;

    /**
     * PLZ of the City. Cannot be empty
     */
    public String address_plz;

    /**
     * The City/Village. Cannot be empty
     */
    public String address_ort;
}