package de.wald_ohne_blaetter.gamelibrary.address;

/**
 * Represents an address in the game library.
 * <p>
 * This class is used as a JPA entity to store relevant information about an address.
 * </p>
 *
 * @author Luke Effer
 * @version 0.0.1
 * @since 2025-09-15
 */

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Address
{
    /**
     * Unique ID of the address. Automatically generated by the database.
     * For locating where the game is stored
     */
    @Id
    private Long address_id;

    /**
     * The street. Cannot be empty
     */
    public String address_street;

    /**
     * house number. Cannot be empty
     */
    public String address_house_number;

    /**
     * PLZ/postal_code of the City. Cannot be empty
     */
    public String address_postal_code;

    /**
     * The City/Village. Cannot be empty
     */
    public String address_ort;
}